name: release

on:
  pull_request:
    types: [ labeled ]
    branches:
      - master

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current version
        shell: bash
        run: |
          CURRENT_VERSION=$(curl -s https://pypi.org/simple/pusher/ | grep -o "pusher-[0-9]*\.[0-9]*\.[0-9]*\.tar\.gz" | tail -1 | grep -o "[0-9]*\.[0-9]*\.[0-9]*")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: pusher/actions
          token: ${{ secrets.PUSHER_CI_GITHUB_PRIVATE_TOKEN }}
          path: .github/actions
      - uses: ./.github/actions/prepare-version-bump
        id: bump
        with:
          current_version: ${{ env.CURRENT_VERSION }}
      - name: Push
        shell: bash
        run: |
          sed -i "s|VERSION = '[^']*'|VERSION = '${{ steps.bump.outputs.new_version }}'|" pusher/version.py

          git add pusher/version.py CHANGELOG.md
          git commit -m "Bump to version ${{ steps.bump.outputs.new_version }}"
          git push
